<a href="https://colab.research.google.com/github/NazmusSaad/2-Diophantine-Approximation/blob/main/Good_Copy_of_2_diophantine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# NEW GOOD COPY
# LLL MATRIX Generating code --> Hardcode for each use case for now becuase the primes can change which means different initial matrix
# Step 0: Precomputation

import numpy as np
import sympy as sp

# Define the two prime numbers
primes = [2, 3]

# Compute the logarithms of the primes
log_primes = [sp.log(p).evalf() for p in primes]

# Construct the 3x2 matrix
initial_matrix = np.array([
    [-2 * log_primes[0], log_primes[1]],
    [-3 * log_primes[0], 2 * log_primes[1]],
    [19 * log_primes[0], -12 * log_primes[1]]
], dtype=np.float64)

# # Construct the 3x2 matrix
# initial_matrix = np.array([
#     [-2, 1],
#     [-3, 2 ],
#     [19, -12 ]
# ], dtype=np.float64)

print("Initial Matrix:")
print(initial_matrix)

def gram_schmidt(B):
    """Performs Gram-Schmidt orthogonalization."""
    n = B.shape[0]  # Number of rows
    m = B.shape[1]  # Number of columns
    U = np.zeros_like(B)
    R = np.zeros((m, m), dtype=np.float64)  # Square matrix R of size m x m

    for i in range(n):
        U[i] = B[i]
        for j in range(min(i, m)):  # Ensure j does not exceed the number of columns
            R[j, min(i, m-1)] = np.dot(U[j], B[i]) / np.dot(U[j], U[j])
            U[i] -= R[j, min(i, m-1)] * U[j]
        if i < m:
            R[i, i] = np.linalg.norm(U[i])

        # If U[i] contains NaN, exit early to prevent infinite loop
        if np.isnan(U[i]).any():
            print(f"Warning: NaN detected in Gram-Schmidt orthogonalization at row {i}.")
            break

    return U, R

def lll_reduction(B, delta=0.75):
    """Applies the LLL algorithm to matrix B."""
    n, m = B.shape
    U, R = gram_schmidt(B)

    k = 1
    max_iterations = 100  # Set a maximum number of iterations to avoid infinite loop
    iteration_count = 0

    while k < n and iteration_count < max_iterations:
        print(f"Iteration {k}:")
        print("Current B matrix:")
        print(B)
        print("Current U matrix:")
        print(U)

        # Size reduction
        for j in range(min(k - 1, m - 1), -1, -1):  # Adjusted range to avoid index errors
            mu = np.dot(B[k], U[j]) / np.dot(U[j], U[j])
            if abs(mu) > 0.5:
                B[k] -= np.round(mu) * B[j]

        U, R = gram_schmidt(B)

        # Check for NaN values in U matrix
        if np.isnan(U).any():
            print("Stopping due to NaN values in U matrix.")
            break

        # Lovasz condition, adjusted for rectangular matrices
        if np.dot(U[k], U[k]) >= (delta - (np.dot(B[k], U[k - 1]) / np.dot(U[k - 1], U[k - 1]))**2) * np.dot(U[k - 1], U[k - 1]):
            k += 1
        else:
            B[[k, k - 1]] = B[[k - 1, k]]
            U, R = gram_schmidt(B)
            k = max(k - 1, 1)

        iteration_count += 1

    if iteration_count >= max_iterations:
        print("Max iterations reached. Exiting to prevent infinite loop.")

    return B

# Apply LLL reduction
lll_reduced_matrix = lll_reduction(initial_matrix)

# Display the LLL-reduced matrix
print("LLL-reduced d_ij matrix:")
print(lll_reduced_matrix)


Initial Matrix:
[[ -1.38629436   1.09861229]
 [ -2.07944154   2.19722458]
 [ 13.16979643 -13.18334746]]
Iteration 1:
Current B matrix:
[[ -1.38629436   1.09861229]
 [ -2.07944154   2.19722458]
 [ 13.16979643 -13.18334746]]
Current U matrix:
[[-1.38629436e+00  1.09861229e+00]
 [ 2.67388038e-01  3.37406138e-01]
 [ 3.77475828e-15  2.88657986e-15]]
Iteration 1:
Current B matrix:
[[  0.69314718   0.        ]
 [ -1.38629436   1.09861229]
 [ 13.16979643 -13.18334746]]
Current U matrix:
[[0.69314718 0.        ]
 [0.         1.09861229]
 [0.         0.        ]]
Iteration 2:
Current B matrix:
[[ 6.93147181e-01  0.00000000e+00]
 [ 2.22044605e-16  1.09861229e+00]
 [ 1.31697964e+01 -1.31833475e+01]]
Current U matrix:
[[0.69314718 0.        ]
 [0.         1.09861229]
 [0.         0.        ]]
Iteration 1:
Current B matrix:
[[6.93147181e-01 0.00000000e+00]
 [1.77635684e-15 0.00000000e+00]
 [2.22044605e-16 1.09861229e+00]]
Current U matrix:
[[0.69314718 0.        ]
 [0.         0.        ]
 [       n

<ipython-input-2-f578b1c5773d>:41: RuntimeWarning: invalid value encountered in scalar divide
  R[j, min(i, m-1)] = np.dot(U[j], B[i]) / np.dot(U[j], U[j])


In [3]:
# factorial
def fact(n):
  if n == 0 or n == 1:
    return 1
  return n*fact(n-1)

In [4]:
import math
# Step 3: Evaluate e^ei using EXP

# EXP : Taylor series expansion of exp(x) series then evaluate using rectangular splitting

def EXP(e):
  N = 100 # number of terms in the series
  p = N//5
  q = N // p
  sum, sum2 = 0, 0

  # Normal
  for k in range(N):
    sum += (math.pow(e, k)/fact(k))

  # Rectangular splitting
  for i in range(p - 1):
    for j in range(q - 1):
        sum2 += (math.pow(e, (p * j + i)) / math.factorial(p * j + i))

  # print(sum, sum2)
  return sum


In [7]:
# Experiment
# e^x function using 2-diophantine approximation
# x is the argument to exp(x), r is the reduction parameter, m is the number of primes
def exp(x):
  m = 2
  r = 6

  # Step 0: Precompute logarithms
  # primes same list as above
  q = log_primes

  # Step 1: Use LLL algo to generate dij matrix
  d = lll_reduced_matrix
  # d = [[-2,1],[-3,2],[19,-12]]
  # d = [[-3,2],[19,-12],[65,-14]]

  print("dij matrix: \n",d)

  # Step 2: Determine coefficients c1, ... , cn
  l = r//m

  # diff ei values for each row of the dij matrix
  e = [0 for i in range(l)]
  # k values used in adjusting x
  k = [0 for i in range(l)]
  # 2d array that will contain the Cj coefficients for each row
  c = []

  # loop thru rows of dij matrix
  for i in range(0,l):

    # adds the 2nd dimension to the array. Contains the Cj for each particular row
    c.append([0 for i in range(m)])

    # loop thru primes
    for j in range(0,m):

      # accumalate ei using the sum(dij*log(m))
      e[i] += d[i][j]*((q[j]))
      # e[i] += d[i][j]

      # print("e[i]: ", e[i], "i: ", i,"j: ", j)

    # k value for each row
    # print("before ki, x:  ei:", x, e[i])
    # print(x/e[i], math.floor(x/e[i]))
    k[i] = math.floor(x/e[i])
    # print("ki: ", k[i])

    # # !!!!!!! Update x  --> This step is only for extremely big numbers
    # print("ji * ei: ", k[i] * e[i])
    # x -= k[i] * e[i]
    # print("Updated x: ", x)

    # loop thru primes again and adjust Cj values for current row i
    for j in range(0,m):
      c[i][j] += k[i] * d[i][j]
      # print("c[j]: ", c[i], "j: ", j)
    # print("C: ",c)
    # print("e: ", e)

    # reconstruction of argument --> error checking purposes
    x2 = c[i][0] * q[0] + c[i][1] * q[1] + e[i]
    # print("reconstructed x: ",x2)

  # print("C: ",c)
  # print("e: ", e)

  # Find a suitable ei
  i = 0
  while (e[i] > 2**(-r)):
    i += 1
  x2 = c[i][0] * q[0] + c[i][1] * q[1] + e[i]
  # print("x2: ",x2)

  # Step 3: Evaluate e^ei using EXP
  e_ei = EXP(e[i])

  # Step 4: Reconstruct
  e_x = e_ei * math.pow(primes[0], c[i][0]) * math.pow(primes[1], c[i][1])
  print("Approximated e^" + str(x) + ":" , e_x)
  print("Actual e^" + str(x) + ":      " , math.exp(x))
  return e_x

In [8]:
exp(4)

dij matrix: 
 [[6.93147181e-01 0.00000000e+00]
 [1.77635684e-15 0.00000000e+00]
 [2.22044605e-16 1.09861229e+00]]
Approximated e^4: 54.59815003314431
Actual e^4:       54.598150033144236


54.59815003314431